source $HOME/git/kjm_tools/aliases

# I use this on headless Ubuntu in ordr to unlock the 
# gnome keyrign after booting.
function unlock()
{
    read -rs "pass?Password: "
    echo
    export $(echo -n "$pass" | gnome-keyring-daemon --daemonize --replace --unlock)
    unset pass
}

source $HOME/git/kjm_tools/fzf/fzftools

