source $HOME/git/kjm_tools/aliases

# I use this on headless Ubuntu in ordr to unlock the 
# gnome keyrign after booting.
function unlock()
{
    read -rsp "Password: " pass
    export $(echo -n "$pass" | gnome-keyring-daemon --daemonize --replace --unlock)
    unset pass
}

source $HOME/git/kjm_tools/fzf/fzftools

export WEBKIT_DISABLE_COMPOSITING_MODE=1
export WEZTERM_LOG=off
